apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iirspk9pl-python
  janus-idp.io/tekton: iirspk9pl-python
  backstage.io/kubernetes-id: iirspk9pl-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iirspk9pl-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
